name: Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Windows"
            os: "windows-latest"
            suffix: "windows"
            ext: ".exe"
          - name: "Linux"
            os: "ubuntu-latest"
            suffix: "linux"
            ext: ""
          - name: "MacOS"
            os: "macos-11"
            suffix: "macos"
            ext: ""
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Instantiate cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Zip artifacts
        run: |
          cd ./target/release
          7z a ../../awty-${{matrix.suffix}}.zip awty${{matrix.ext}}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          files: awty-${{matrix.suffix}}.zip
